export const TENANT_PRODUCT_IDS = ["qms", "em", "ccv"] as const;
export type TenantProductId = (typeof TENANT_PRODUCT_IDS)[number];

export const TENANT_TIERS = ["starter", "professional", "enterprise"] as const;

export const TENANT_REGION_OPTIONS = [
  { value: "us-east-1", labelKey: "region_us_east_1" },
  { value: "us-west-2", labelKey: "region_us_west_2" },
  { value: "eu-west-1", labelKey: "region_eu_west_1" },
] as const;

export const TENANT_ADMIN_LABELS = {
  pageTitle: "Tenant administration",
  newTenantCta: "New tenant",
  listTitle: "Tenants",
  listSubtitle:
    "Create tenants with company details; the primary contact receives a welcome email with login credentials.",
  product_qms: "QMS",
  product_em: "EM",
  product_ccv: "CCV",
  tier_starter: "Starter",
  tier_professional: "Professional",
  tier_enterprise: "Enterprise",
  region_us_east_1: "US East (N. Virginia)",
  region_us_west_2: "US West (Oregon)",
  region_eu_west_1: "EU West (Ireland)",
  section_core: "Workspace",
  section_contact: "Primary contact & admin",
  section_company: "Company",
  section_address: "Address",
  section_billing: "Billing",
  section_defaults: "Defaults",
  billing_same_as_primary: "Billing address matches primary address",
  submitCreating: "Creating…",
  submitCreate: "Create tenant",
  field_workspace_name: "Workspace / tenant name",
  field_products: "Products",
  field_tier: "Tier",
  field_region: "Region",
  field_primary_first_name: "First name",
  field_primary_last_name: "Last name",
  field_primary_email: "Admin email",
  field_primary_phone: "Phone",
  field_company_website: "Website",
  field_company_industry: "Industry",
  field_company_notes: "Notes",
  field_timezone: "Timezone",
  field_locale: "Locale",
  field_max_users: "Max users",
  field_max_storage: "Max storage (GB)",
  action_save: "Save",
  action_delete_tenant: "Delete tenant…",
  action_edit: "Edit",
  action_resend_welcome: "Resend welcome email",
  action_resend_welcome_aria: "Send welcome email again with a new temporary password",
  resend_welcome_success: "Welcome email sent. The tenant admin will receive a new temporary password.",
  resend_welcome_error: "Could not resend the welcome email. Try again or check services and SMTP settings.",
  action_settings: "Settings",
  back_to_list: "Back to list",
  profile_section: "Profile & onboarding",
  delete_confirm_title: "Delete tenant?",
  delete_confirm_desc:
    "This soft-deletes the tenant. Billing and provisioning data remains for operations to review.",
  settings_title: "Tenant settings",
  settings_saved: "Settings saved",
  card_limits_locale: "Limits & locale",
  field_address_line1: "Address line 1",
  field_address_line2: "Address line 2",
  field_city: "City",
  field_state: "State",
  field_country: "Country",
  field_postal_code: "Postal code",
  field_tax_id: "Tax ID",
  field_billing_email: "Billing email",
  field_billing_phone: "Billing phone",
  field_billing_address_line1: "Billing address line 1",
  field_billing_address_line2: "Billing address line 2",
  field_billing_city: "Billing city",
  field_billing_state: "Billing state",
  field_billing_country: "Billing country",
  field_billing_postal_code: "Billing postal code",
  detail_workspace_card: "Workspace",
  detail_primary_contact_card: "Primary contact",
  detail_profile_snapshot: "Company & billing snapshot",
  detail_all_users: "All users in this tenant",
  detail_back_link: "Back to tenants",
  detail_value_empty: "—",
  list_loading_count: "Loading…",
  list_search_placeholder: "Search by name or slug…",
  list_filter_all_status: "All statuses",
  list_filter_active: "Active",
  list_filter_suspended: "Suspended",
  list_filter_inactive: "Inactive",
  list_col_tenant: "Tenant",
  list_col_tier: "Tier",
  list_col_products: "Products",
  list_col_status: "Status",
  list_col_region: "Region",
  list_col_created: "Created",
  list_col_actions: "Actions",
  list_open: "Open",
  list_suspend: "Suspend",
  list_activate: "Activate",
  list_no_actions: "—",
  list_page_prefix: "Page",
  list_page_of: "of",
  tenant_status_active: "Active",
  tenant_status_inactive: "Inactive",
  tenant_status_suspended: "Suspended",
  tenant_status_pending: "Pending",
  tenant_status_provisioning: "Provisioning",
  tenant_status_provisioning_failed: "Failed",
  detail_label_status: "Status",
  detail_label_tier: "Tier",
  detail_label_region: "Region",
  detail_label_products: "Products",
  detail_label_id: "ID",
  detail_label_name: "Name",
  detail_label_email: "Email",
  detail_label_phone: "Phone",
  detail_not_found: "Tenant not found, or you do not have access to this slug.",
  detail_users_empty: "No users matched this tenant in the directory response.",
  list_prev_page: "Previous page",
  list_next_page: "Next page",
  directory_col_user: "User",
  directory_col_role: "Role",
  directory_col_status: "Status",
  role_super_admin: "Super Admin",
  role_tenant_admin: "Tenant Admin",
  role_tenant_user: "User",
} as const;
