{{- if .Values.serviceAccount.create }}
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-sa
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- include "rainer-platform.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml $.Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
{{- end }}
