---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rainer-platform-default-deny
  namespace: rainer-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: rainer-platform
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-platform
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-platform
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-infra
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9092
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-monitoring
      ports:
        - protocol: TCP
          port: 9090
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-ingress
  namespace: rainer-platform
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kong-system
      ports:
        - protocol: TCP
          port: 8000
