---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rainer-ccv-default-deny
  namespace: rainer-ccv
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-intra-namespace
  namespace: rainer-ccv
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-ccv
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-ccv
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-infra
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 9092
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-monitoring
      ports:
        - protocol: TCP
          port: 9090
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-platform-to-ccv
  namespace: rainer-ccv
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: rainer-platform
      ports:
        - protocol: TCP
          port: 8040
        - protocol: TCP
          port: 8041
        - protocol: TCP
          port: 8042
        - protocol: TCP
          port: 8043
        - protocol: TCP
          port: 8044
